// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Company struct {
	ID        int64
	Name      sql.NullString
	CreatedAt time.Time
}

type User struct {
	ID                int64
	FirstName         string
	LastName          string
	Email             string
	EncryptedPassword string
	CreatedAt         time.Time
	CompanyID         int64
}
